apiVersion: apps/v1
kind: Deployment
metadata:
  name: aggregator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aggregator
  template:
    metadata:
      labels:
        app: aggregator
    spec:
      containers:
      - name: aggregator
        image: aggregator:latest
        imagePullPolicy: Never
        env:
        - name: PORT
          value: "8080"
        - name: NUM_NODES
          value: "3"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: aggregator
spec:
  selector:
    app: aggregator
  ports:
  - port: 8080
    targetPort: 8080
  type: ClusterIP 