apiVersion: apps/v1
kind: Deployment
metadata:
  name: performance-status
spec:
  replicas: 3
  selector:
    matchLabels:
      app: performance-status
  template:
    metadata:
      labels:
        app: performance-status
    spec:
      containers:
      - name: performance-status
        image: performance-status:latest
        imagePullPolicy: Never
        env:
        - name: PORT
          value: "8080"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: performance-status
spec:
  selector:
    app: performance-status
  ports:
  - port: 8080
    targetPort: 8080
  type: ClusterIP 